version: 2.1

jobs:
  checks:
    docker:
      - image: corebreaker/rust-devtools-circleci:rust-1.80.0-v0.3.14
    steps:
      - checkout
      - run:
          name: Show Env
          command: /bin/sh -c set
      - run:
          name: Check formatting
          command: cargo +nightly fmt -- --config-path .circleci/fmt.toml --check

  coverage:
    docker:
      - image: corebreaker/rust-devtools-circleci:rust-1.80.0-v0.3.14
    steps:
      - checkout
      - run:
          name: Make coverage
          command: coverage.sh -i './tests/**' -i './src/components/**'
      - run:
          name: Upload Coverage Result To Coveralls
          command: coveralls circleci -r yew-reactor -D target -t $COVERALLS_REPO_TOKEN target/coverage/coveralls.json
      - store_artifacts:
          path: target/coverage

  test:
    docker:
      - image: cimg/rust:1.79.0
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: CARGO_NET_GIT_FETCH_WITH_CLI=true cargo test --lib
      - run:
          name: Run Cucumber tests
          command: CARGO_NET_GIT_FETCH_WITH_CLI=true cargo test --test cucumber --features task-spawner

workflows:
  coverage:
    jobs:
      - coverage

  all-tests:
    jobs:
      - checks
      - test
