[package]
name = "example-loop"
version.workspace = true
edition.workspace = true

[dependencies]
yew = { workspace = true }
gloo-console = { workspace = true }
yew-reactor = { path = "../../packages/yew-reactor", package = "yew-reactor", features = ["wasm"] }
